# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hHVhggUIzyw5JGkVP1auesPh5TNTAiKH
"""

from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

dataset=pd.read_csv('recipe2.csv')

X = dataset.drop(['serial','title','rating'],axis=1)
dataset['RatingClass']=dataset['RatingClass'].replace({'Excellent':'2','Good':'1','Average':'0'})

X=dataset[['preptime', 'cooktime', 'totaltime',
       'servings', 'ingredients',
       'steps']]
y=dataset['RatingClass']

from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=123)

model=Sequential()
model.add(Dense(12,input_dim=6,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(3 ,activation='softmax'))

classifier .compile(loss="categorical_crossentropy",optimizer="adam",metrics=['accuracy'])
model.fit(X_train,y_train,epochs=10,batch_size=10)

scores1=model.evaluate(X_train,y_train)
print("Training Accuracy")
print(model.metrics_names[1],scores1[1]*100)

scores2=model.predict(X_test)

print("Testing Accuracy")
print(model.metrics_names[1],scores2[1]*100)